server:
  port: 8080
  servlet:
    context-path: /api/book-store

spring:
  main:
    allow-bean-definition-overriding: false
  devtools:
    add-properties: false
  datasource:
    url: jdbc:h2:mem:bookstore
    username: admin
    password: password
    driver-class-name: org.h2.Driver
  sql:
    init:
      platform: h2
      mode: embedded
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

logging:
  file:
    name: /apps/book-store/book-store.log
  level:
    root: info
    web: debug
    sql: debug

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,logfile
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
  health:
    defaults:
      enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
