DROP TABLE BOOKS IF EXISTS;
CREATE TABLE IF NOT EXISTS BOOKS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    AUTHOR VARCHAR(255) NOT NULL,
    ISBN VARCHAR(255) NOT NULL,
    LANGUAGE VARCHAR(255) NOT NULL,
    NUMBER_OF_BOOKS INTEGER NOT NULL,
    CREATED DATE DEFAULT NOW()
);